trigger:
- master

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 0
      revision: 2
      projectPath: 'Extensions/FluidTest.AzureSearch/FluidTest.AzureSearch.csproj'