trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - Engine/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 2
      minor: 0
      patch: 0
      revision: 3
      projectPath: 'Engine/Marktek.Fluent.Testing.Engine.csproj'