# File: azure-pipelines.yml
trigger:
- master

extends:
  template: pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 0
      revision: 0
      projectPath: 'Extensions/AzureSearch/FluidTest.AzureSearch/FluidTest.AzureSearch.csproj'