trigger:
- master

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 0
      revision: 0
      projectPath: 'Extensions/FluidTest.AzureStorage/FluidTest.AzureStorage.csproj'